"""empty message

Revision ID: e5f67a9afe0e
Revises: a587253b6ada
Create Date: 2026-06-25 19:50:22.726007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f67a9afe0e'
down_revision: Union[str, None] = 'a587253b6ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollback_plans',
    sa.Column('rollback_plan_id', sa.String(length=36), nullable=False),
    sa.Column('execution_plan_id', sa.String(length=36), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_plan_id'], ['execution_plans.execution_plan_id'], ),
    sa.PrimaryKeyConstraint('rollback_plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollback_plans')
    # ### end Alembic commands ###
